### ISSUE TITLE
可不可以将每一小节的内容整理成markdown文档放在每个topic文件夹下？

### ISSUE THREAD

**Issue by ichdream** [FengJungle/DesignPattern#2]
写得很不错。
每次查看文档需要打开csdn，比较喜欢markdown文档风格。
那么，是不是可以来个需求，将csdn上的文章转换成md文档放在每个相应的文件夹下面，这样查看阅读也更加方便些。
你觉得呢？
如果可以的话，我愿意做这份搬砖工作，提pr.

**Comment by FengJungle** [comment]
很感谢你的建议，如今我也更习惯和喜欢md的风格。
这是一个很好的建议，我将会逐步开始这项工作。
只是个人精力有限，如果能够有朋友们分担，那将会更高效！
再次感谢！

**Comment by FengJungle** [comment]
> 写得很不错。
> 每次查看文档需要打开csdn，比较喜欢markdown文档风格。
> 那么，是不是可以来个需求，将csdn上的文章转换成md文档放在每个相应的文件夹下面，这样查看阅读也更加方便些。
> 你觉得呢？
> 如果可以的话，我愿意做这份搬砖工作，提pr.

很感谢你的建议，如今我也更习惯和喜欢md的风格。
这是一个很好的建议，我将会逐步开始这项工作。
只是个人精力有限，如果能够有朋友们分担，那将会更高效！
再次感谢！

**Comment by FengJungle** [comment]
> 写得很不错。
> 每次查看文档需要打开csdn，比较喜欢markdown文档风格。
> 那么，是不是可以来个需求，将csdn上的文章转换成md文档放在每个相应的文件夹下面，这样查看阅读也更加方便些。
> 你觉得呢？
> 如果可以的话，我愿意做这份搬砖工作，提pr.

今晚尝试将第一篇转为markdown格式，需要向您请教下，如何插入图片？我之前只在本地插入过，但push到仓库后就不显示了。还请指教，谢谢。

**Comment by ichdream** [comment]
> > 写得很不错。
> > 每次查看文档需要打开csdn，比较喜欢markdown文档风格。
> > 那么，是不是可以来个需求，将csdn上的文章转换成md文档放在每个相应的文件夹下面，这样查看阅读也更加方便些。
> > 你觉得呢？
> > 如果可以的话，我愿意做这份搬砖工作，提pr.
> 
> 今晚尝试将第一篇转为markdown格式，需要向您请教下，如何插入图片？我之前只在本地插入过，但push到仓库后就不显示了。还请指教，谢谢。

的确，图片显示是一个问题。我写的md文档如果有图片，则显示异常。访问的时候，翻墙则显示没有问题。
我一块，也没有找到好的方法。
另外，有一个办法就是把图片放到图片存放服务器上，俗称“图床”。
之前有几家专门做这个的：
- 七牛云
- 阿里云图床，🤔，这个我不确定有
- 。。。。。

**Comment by FengJungle** [comment]
> > > 写得很不错。
> > > 每次查看文档需要打开csdn，比较喜欢markdown文档风格。
> > > 那么，是不是可以来个需求，将csdn上的文章转换成md文档放在每个相应的文件夹下面，这样查看阅读也更加方便些。
> > > 你觉得呢？
> > > 如果可以的话，我愿意做这份搬砖工作，提pr.
> > 
> > 
> > 今晚尝试将第一篇转为markdown格式，需要向您请教下，如何插入图片？我之前只在本地插入过，但push到仓库后就不显示了。还请指教，谢谢。
> 
> 的确，图片显示是一个问题。我写的md文档如果有图片，则显示异常。访问的时候，翻墙则显示没有问题。
> 我一块，也没有找到好的方法。
> 另外，有一个办法就是把图片放到图片存放服务器上，俗称“图床”。
> 之前有几家专门做这个的：
> 
> * 七牛云
> * 阿里云图床，🤔，这个我不确定有
> * 。。。。。

目前完成两篇了，继续work！

**Comment by ichdream** [comment]
> > > > 写得很不错。
> > > > 每次查看文档需要打开csdn，比较喜欢markdown文档风格。
> > > > 那么，是不是可以来个需求，将csdn上的文章转换成md文档放在每个相应的文件夹下面，这样查看阅读也更加方便些。
> > > > 你觉得呢？
> > > > 如果可以的话，我愿意做这份搬砖工作，提pr.
> > > 
> > > 
> > > 今晚尝试将第一篇转为markdown格式，需要向您请教下，如何插入图片？我之前只在本地插入过，但push到仓库后就不显示了。还请指教，谢谢。
> > 
> > 
> > 的确，图片显示是一个问题。我写的md文档如果有图片，则显示异常。访问的时候，翻墙则显示没有问题。
> > 我一块，也没有找到好的方法。
> > 另外，有一个办法就是把图片放到图片存放服务器上，俗称“图床”。
> > 之前有几家专门做这个的：
> > 
> > * 七牛云
> > * 阿里云图床，🤔，这个我不确定有
> > * 。。。。。
> 
> 目前完成两篇了，继续work！

👀，加油🍻
