### ISSUE TITLE
【文件编码格式问题】linux平台下中文乱码

### ISSUE THREAD

**Issue by ichdream** [FengJungle/DesignPattern#3]
![image](https://user-images.githubusercontent.com/11766177/131322350-93d2b52a-7710-4837-9f34-3c24eafc3402.png)

开发环境为：ubuntu x_86_64
编译器：gcc/g++

经过排查发现，是因为代码文件的编码为GB2312

作者应该是在Windows上开发的吧，那么为了兼容，后续要不要改为utf-8文件格式？

我改了格式后，问题解决了。

**Comment by FengJungle** [comment]
> ![image](https://user-images.githubusercontent.com/11766177/131322350-93d2b52a-7710-4837-9f34-3c24eafc3402.png)
> 
> 开发环境为：ubuntu x_86_64
> 编译器：gcc/g++
> 
> 经过排查发现，是因为代码文件的编码为GB2312
> 
> 作者应该是在Windows上开发的吧，那么为了兼容，后续要不要改为utf-8文件格式？
> 
> 我改了格式后，问题解决了。

嗯是的，我当时写代码的时候是在windows 平台上完成的，未考虑到平台兼容性问题，在此感到抱歉。

**Comment by ichdream** [comment]
> > ![image](https://user-images.githubusercontent.com/11766177/131322350-93d2b52a-7710-4837-9f34-3c24eafc3402.png)
> > 开发环境为：ubuntu x_86_64
> > 编译器：gcc/g++
> > 经过排查发现，是因为代码文件的编码为GB2312
> > 作者应该是在Windows上开发的吧，那么为了兼容，后续要不要改为utf-8文件格式？
> > 我改了格式后，问题解决了。
> 
> 嗯是的，我当时写代码的时候是在windows 平台上完成的，未考虑到平台兼容性问题，在此感到抱歉。

这个没有关系，稍微更改一下就好了。
🤝
👍
😊
🍻
