### ISSUE TITLE
缺少markdown

### ISSUE THREAD

**Issue by as754770178** [FengJungle/DesignPattern#7]
有几章内容没有markdown文件

**Comment by huermosy** [comment]
是的，你有找到补充的吗，后面几章都没有markdown貌似.

**Comment by unknow233** [comment]
疑似csdn 圈钱

**Comment by FengJungle** [comment]
公众号 Jungle笔记里有原文哈，可以在公众号看看，等空闲了我把md整理下更新在这

**Comment by FengJungle** [comment]
这几天我会逐渐补充过来，每天搞一点

**Comment by FengJungle** [comment]
> 有几章内容没有markdown文件

已经补充完毕

**Comment by FengJungle** [comment]
> 是的，你有找到补充的吗，后面几章都没有markdown貌似.

已经补充完毕

**Comment by FengJungle** [comment]
Done!
