### ISSUE TITLE
重复析构

### ISSUE THREAD

**Issue by sun514011664** [FengJungle/DesignPattern#8]
05.PrototypePattern/2.Code/main.cpp 
#53 	delete jungleModel;

主函数中析构了jungleModel
而在jungleWork的析构函数中又一次析构了jungleModel。

**Comment by FengJungle** [comment]
Thanks. I have fixed it and commit.

**Comment by sun514011664** [comment]
您好，    您的邮件已收到（来自QQ邮箱的自动回复）。                                              ——孙小柒
